/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.4.1/userguide/multi_project_builds.html
 */

rootProject.name = "Mosaic"

pluginManagement {
    includeBuild("build-logic")
}

include("mosaic-core")
include("mosaic-test")

// Future modules can be added here:
// include("mosaic-api")
// include("mosaic-web")
// include("mosaic-cli")
