name: 🚀 Feature Request
description: Suggest an idea for Mosaic
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
  - type: textarea
    attributes:
      label: Additional Context