name: Build Badge

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Compilation Only
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build project (compilation only)
      run: ./gradlew assemble --no-daemon
      # This runs compilation only:
      # - compileKotlin (main source compilation)
      # - jar (artifact generation)
      # - assemble (all output artifacts)
      # NO tests, NO style checks, NO quality checks


