name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: zulu
        cache: gradle

    - name: Run comprehensive PR validation
      run: ./gradlew check --no-daemon --info
      # This runs the most comprehensive validation including:
      # - Compilation (compileKotlin, compileJava)
      # - Tests (test with coverage - koverHtmlReport, koverVerify)
      # - Code quality (ktlintCheck, detekt)
      # - Coverage verification (koverCachedVerify)
      # - All verification tasks across all projects

    - name: Generate XML coverage report (for debugging)
      if: failure()
      run: ./gradlew koverXmlReport --no-daemon

    - name: Verify build artifacts
      if: failure()
      run: |
        echo "Verifying build artifacts..."
        find . -path "**/build/reports/*" -type d | grep -E "(detekt|kover|ktlint|tests)" | wc -l
        echo "Build verification complete"

    - name: Upload build reports (only on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-reports
        path: |
          **/build/reports/
        retention-days: 7
