name: Test Badge

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: zulu
        cache: gradle

    - name: Run tests
      run: ./gradlew test --no-daemon
      # This runs tests only:
      # - compileKotlin (compilation dependency)
      # - compileTestKotlin (test compilation)
      # - test (unit tests with coverage)
      # - koverHtmlReport (coverage report generation)
      # NO style checks (ktlint/detekt), NO koverVerify


